name: Automated Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    # Steps this job must take to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
