name: Publish to npm on Tag

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Trigger on tags that start with 'v'

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use your npm token secret
        run: npm publish
